version: '3.5'

services:
  pgsql:
    image: postgres:15
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: db
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: a@a.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - '8080:80'
